name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment:
      name: production   # requires approval if protected
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply (manual approval required)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan
